name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build_test_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Build the app
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN}}
        run: npm install

      - name: Lint
        if: success()
        run: npm run lint

      - name: Test
        if: success()
        run: npm run test

      - name: Deploy
        if: success() && github.event_name == 'push'
        run: npm run ng deploy -- --name='Deploy Dummy' --email='deploy@webtrix.be'
