name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build_lint_test_deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ '14.17.6' ]

    steps:
      - name: Build the app
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: CYPRESS_INSTALL_BINARY=0 npm install

      - name: Lint
        if: success()
        run: npm run lint

      - name: Test
        if: success()
        run: npm run test

      - name: Deploy
        if: success() && github.event_name == 'push'
        run: npm run deploy
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
